[[redirects]]
from = "/post/aggregate-design-transactional-consistency"
to = "/guides/aggregate-design-transactional-consistency"

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
    './out/404.html',
]
