[[redirects]]
from = "/post/aggregate-design-transactional-consistency"
to = "/blog/aggregate-design-transactional-consistency"

[[redirects]]
from = "/guides/*"
to = "/blog/:splat"

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
exclude = [
    './out/404.html',
]
